settings:
  server-ip: "example.net" #server ip | https://namemc.com/server/example.net #It would be "example.net"
  placeholder-api: true
  verify-command-permission: "verify.access"
  namemc-command-permission: "admin.verify.access"
  randomize-rewards: true
  amount-of-rewards: 2

rewards:
  reward1:
    item:
      enabled: true
      info: "DIRT:32:0:&cHi" #material:amount:data:name
      lore:
        - ""
      enchants:
        - ""
    command:
      enabled: true
      commands:
        - "give {player} dirt 1"

data:
  liked: {}